export const CONTENT = {
  level1: [
    {
      id: "l1-1",
      text: "City council approved a 3% bus fare increase after a 5-4 vote on Tuesday night.",
      answer: "true",
      explanation: "Specific vote counts and a bounded claim read like a report, not hype.",
    },
    {
      id: "l1-2",
      text: "Doctors confirm this one kitchen spice cures memory loss overnight.",
      answer: "misleading",
      explanation: "Absolute cure claims with no evidence are classic misinformation packaging.",
    },
    {
      id: "l1-3",
      text: "A district audit found the school finished the quarter $1.2 million under budget.",
      answer: "true",
      explanation: "The statement is measurable and restrained, without emotional inflation.",
    },
    {
      id: "l1-4",
      text: "Experts are panicking because this common phone setting is secretly destroying your brain.",
      answer: "misleading",
      explanation: "Loaded language and vague unnamed experts are red flags.",
    },
    {
      id: "l1-5",
      text: "The labor department reported unemployment declined from 5.4% to 5.1% in March.",
      answer: "true",
      explanation: "It states a concrete statistic with a source and timeframe.",
    },
    {
      id: "l1-6",
      text: "This viral tea melts ten pounds in a week and doctors hate it.",
      answer: "misleading",
      explanation: "Sensational phrasing and impossible performance claims indicate manipulation.",
    },
    {
      id: "l1-7",
      text: "The museum will extend weekend hours beginning May 10, according to its public calendar.",
      answer: "true",
      explanation: "A logistical update tied to a public source is straightforward reporting.",
    },
    {
      id: "l1-8",
      text: "Scientists admit climate change was exaggerated to scare taxpayers.",
      answer: "misleading",
      explanation: "The phrasing implies a broad admission without evidence or identifiable sources.",
    },
    {
      id: "l1-9",
      text: "The university said freshman applications rose 8% year over year.",
      answer: "true",
      explanation: "It is a narrow claim with a clear owner and quantifiable value.",
    },
    {
      id: "l1-10",
      text: "One secret loophole lets anyone avoid paying rent legally forever.",
      answer: "misleading",
      explanation: "Universal promises and secret loopholes are typical clickbait signals.",
    },
  ],
  level2: [
    {
      id: "l2-1",
      text: "Either you support this policy or you hate your country.",
      answer: "false dichotomy",
      explanation: "The statement collapses a complex policy debate into two extreme choices.",
    },
    {
      id: "l2-2",
      text: "Everyone knows this plan is the only solution left.",
      answer: "manufactured consensus",
      explanation: "It invokes universal agreement instead of evidence.",
    },
    {
      id: "l2-3",
      text: "Why criticize this decision when the previous administration caused worse problems?",
      answer: "whataboutism",
      explanation: "It deflects the criticism by changing the target.",
    },
    {
      id: "l2-4",
      text: "This disastrous, shameful tax scheme is crushing honest families.",
      answer: "loaded language",
      explanation: "Emotionally charged adjectives are doing the persuasion work.",
    },
    {
      id: "l2-5",
      text: "One successful pilot program proves the nationwide rollout cannot fail.",
      answer: "cherry-picking",
      explanation: "It relies on a single positive case while ignoring the wider evidence base.",
    },
    {
      id: "l2-6",
      text: "No reasonable parent could possibly disagree with this curriculum ban.",
      answer: "manufactured consensus",
      explanation: "The statement pressures the audience by implying agreement is universal and dissent is irrational.",
    },
    {
      id: "l2-7",
      text: "The corrupt bureaucrats shoved through another disgusting rule.",
      answer: "loaded language",
      explanation: "The sentence primes emotion through hostile wording rather than argument.",
    },
    {
      id: "l2-8",
      text: "The report highlights the best month on record and ignores the rest of the year.",
      answer: "cherry-picking",
      explanation: "A selectively chosen data point is being used as the whole story.",
    },
    {
      id: "l2-9",
      text: "You can either close the border immediately or accept total chaos.",
      answer: "false dichotomy",
      explanation: "It frames policy options as only two outcomes.",
    },
    {
      id: "l2-10",
      text: "Why are we discussing this scandal when the other party did something far worse?",
      answer: "whataboutism",
      explanation: "It redirects scrutiny instead of answering the original issue.",
    },
  ],
  level3: [
    {
      id: "l3-1",
      text: "Only a fool would doubt this heroic reform package.",
      answer: "loaded language",
      explanation: "The line labels dissenters negatively to pressure agreement.",
    },
    {
      id: "l3-2",
      text: "If we do not ban the platform now, society will collapse.",
      answer: "false dichotomy",
      explanation: "It presents a single policy choice as the only barrier against catastrophe.",
    },
    {
      id: "l3-3",
      text: "Every serious analyst supports the merger, so debate is over.",
      answer: "manufactured consensus",
      explanation: "It declares an artificial unanimous agreement to close discussion.",
    },
    {
      id: "l3-4",
      text: "The mayor cites one favorable crime statistic and ignores every other category.",
      answer: "cherry-picking",
      explanation: "A selective metric is being used to overstate success.",
    },
    {
      id: "l3-5",
      text: "Why focus on this minister's lies when rival governments lied too?",
      answer: "whataboutism",
      explanation: "The response evades the allegation by shifting focus elsewhere.",
    },
    {
      id: "l3-6",
      text: "Any compassionate voter must back this emergency spending package.",
      answer: "loaded language",
      explanation: "It uses moralized wording to frame one answer as ethically mandatory.",
    },
    {
      id: "l3-7",
      text: "Either we approve the surveillance bill or we surrender to lawlessness.",
      answer: "false dichotomy",
      explanation: "It excludes middle-ground or alternative policies.",
    },
    {
      id: "l3-8",
      text: "People everywhere are begging for this reform, so only extremists oppose it.",
      answer: "manufactured consensus",
      explanation: "It inflates support and stigmatizes dissent instead of showing evidence.",
    },
    {
      id: "l3-9",
      text: "The campaign ad shows the one quarter wages rose and omits the longer decline.",
      answer: "cherry-picking",
      explanation: "The speaker highlights the best sliver of evidence and hides the rest.",
    },
    {
      id: "l3-10",
      text: "Why interrogate this business leader when foreign companies pollute even more?",
      answer: "whataboutism",
      explanation: "It changes the subject from the current claim to another offender.",
    },
  ],
  level4: [
    {
      id: "l4-1",
      text: "The city pilot reduced commute times in one district, though officials say the broader rollout still lacks long-term cost data.",
      answer: "true",
      explanation: "The statement is nuanced and includes its own limitation instead of overselling the result.",
    },
    {
      id: "l4-2",
      text: "A small lab study found a correlation, which proves the supplement prevents depression in everyone.",
      answer: "misleading",
      explanation: "It turns a limited correlation into universal proof.",
    },
    {
      id: "l4-3",
      text: "The governor cited a drop in one crime category while independent analysts noted overall violent crime remained flat.",
      answer: "true",
      explanation: "The statement reports both the claim and the limiting context.",
    },
    {
      id: "l4-4",
      text: "Researchers say the economy is clearly booming because luxury spending rose in one wealthy zip code.",
      answer: "misleading",
      explanation: "It generalizes from an unrepresentative slice of the population.",
    },
    {
      id: "l4-5",
      text: "Officials confirmed the bridge is safe to reopen, but only for light traffic while repairs continue.",
      answer: "true",
      explanation: "The statement is qualified and does not overstate the reopening.",
    },
    {
      id: "l4-6",
      text: "Parents are fleeing public schools in droves, according to a survey of 22 members of one advocacy group.",
      answer: "misleading",
      explanation: "It exaggerates broad behavior from a tiny biased sample.",
    },
    {
      id: "l4-7",
      text: "The report found emissions fell 4% last year, though they remain above pre-2020 levels.",
      answer: "true",
      explanation: "It gives a bounded positive change with an important qualifier.",
    },
    {
      id: "l4-8",
      text: "Because two cities improved test scores after banning phones, the policy is guaranteed to work everywhere.",
      answer: "misleading",
      explanation: "It claims certainty from a small number of cases.",
    },
    {
      id: "l4-9",
      text: "The health agency said the vaccine reduced severe illness, while researchers continue monitoring rare side effects.",
      answer: "true",
      explanation: "The statement includes benefit and uncertainty without distortion.",
    },
    {
      id: "l4-10",
      text: "A single video clip proves the protest movement was violent from the start.",
      answer: "misleading",
      explanation: "It generalizes from one dramatic example to an entire movement.",
    },
  ],
  level5: [
    {
      id: "l5-1",
      trueText: "The transit board delayed the fare vote until next month after requesting an updated budget memo.",
      fakeText: "The transit board secretly tripled fares at midnight and hid the vote from the public.",
      explanation: "The fake line uses conspiracy framing and inflated claims without grounding.",
    },
    {
      id: "l5-2",
      trueText: "The state expanded free school meals for an additional 12 rural districts this semester.",
      fakeText: "The state admitted it has no food plan at all and children will fend for themselves.",
      explanation: "The fake version jumps to dramatic abandonment language unsupported by the policy context.",
    },
    {
      id: "l5-3",
      trueText: "Researchers said the drought outlook improved slightly after April rainfall.",
      fakeText: "Scientists declared the drought over forever after one week of rain.",
      explanation: "The fabricated option turns a modest update into an impossible permanent conclusion.",
    },
    {
      id: "l5-4",
      trueText: "The hospital opened a temporary overflow ward to manage seasonal demand.",
      fakeText: "The hospital collapsed into total chaos and stopped treating ordinary patients entirely.",
      explanation: "The fake statement dramatizes strain into systemic collapse.",
    },
    {
      id: "l5-5",
      trueText: "The university froze tuition for in-state students for the coming academic year.",
      fakeText: "The university abolished tuition overnight because it can now run on donations alone.",
      explanation: "The fake statement uses unrealistic absolute policy change.",
    },
    {
      id: "l5-6",
      trueText: "The mayor's office released revised housing targets after developers missed the first benchmark.",
      fakeText: "The mayor confessed the housing plan was a total scam from day one.",
      explanation: "The fake option replaces administrative revision with scandal language.",
    },
    {
      id: "l5-7",
      trueText: "The farm bureau requested emergency irrigation support as reservoir levels dropped.",
      fakeText: "Farmers say the government wants crops to fail so imports can take over.",
      explanation: "The fake statement inserts motive and conspiracy unsupported by the underlying issue.",
    },
    {
      id: "l5-8",
      trueText: "A regional rail strike was narrowly avoided after overnight contract talks.",
      fakeText: "Rail workers seized the network and shut the whole country down without warning.",
      explanation: "The fabricated option escalates labor negotiations into sensational collapse.",
    },
    {
      id: "l5-9",
      trueText: "The public library added weekend language classes after demand grew last quarter.",
      fakeText: "The public library is replacing books with propaganda workshops every weekend.",
      explanation: "The fake version injects ideological framing to generate alarm.",
    },
    {
      id: "l5-10",
      trueText: "The utility company said outage restoration would continue through the evening.",
      fakeText: "The utility company abandoned the grid and left whole towns without any rescue plan.",
      explanation: "The fake sentence converts a delay into intentional abandonment.",
    },
  ],
  level6: [
    "Frame a school budget cut as if every serious parent already supports it.",
    "Defend a weak policy by forcing the reader into only two choices.",
    "Write a sentence that distracts from criticism by pointing to someone else.",
    "Sell a routine regulation using highly emotional adjectives.",
    "Promote a policy by citing only one favorable statistic.",
    "Describe a tech company scandal by shifting blame to rival firms.",
    "Pitch a healthcare reform as the only moral option.",
    "Make a transit overhaul sound universally accepted without evidence.",
    "Argue for stricter policing by using one extreme example as the whole story.",
    "Write a campaign line that sounds urgent, emotional, and manipulative.",
  ],
};
