//
//  LegalTabView.swift
//  SniffTest
//
//  Created by Alina Andreieva on 21/4/26.
//

import SwiftUI

struct LegalTabView: View {
    @State private var expandedSections: Set<String> = ["Eligibility and Use Conditions"]

    private let sections: [LegalSection] = [
        LegalSection(
            title: "Eligibility and Use Conditions",
            paragraphs: [
                "This platform is intended for users aged 16 and above. By accessing or using the application, users confirm that they meet this requirement.",
                "For users under the age of 16, the use of the platform is recommended under parental or educational supervision.",
                "Users agree to use the platform for educational purposes only. The platform shall not be used as a source of definitive information or relied upon for legal, professional, or decision-making purposes.",
                "The developers shall not be held responsible for any decisions made based on the interpretation or misuse of the outputs generated by the system."
            ]
        ),
        LegalSection(
            title: "Legal & Regulatory Framework",
            paragraphs: [
                "This platform operates at the intersection of artificial intelligence, freedom of expression, and information integrity. Its design is grounded in both European and Ukrainian legal standards.",
                "1. Freedom of Expression and Information Integrity",
                "The platform is developed in accordance with Article 10 of the European Convention on Human Rights, which guarantees the right to freedom of expression, including the freedom to receive and impart information without interference by public authorities.",
                "In Ukrainian legislation, this principle is reflected in Article 34 of the Constitution of Ukraine, which ensures freedom of thought and speech, as well as the right to freely collect, store, use, and disseminate information.",
                "The platform does not restrict or moderate content. Instead, it adopts a non-interventionist approach by strengthening users’ ability to independently assess information, in line with European standards on countering disinformation through media literacy rather than censorship.",
                "2. Artificial Intelligence Regulation",
                "The system is designed in accordance with the EU Artificial Intelligence Act (Regulation (EU) 2024/1689).",
                "The platform does not fall within the category of high-risk AI systems, as defined in Article 6 and Annex III of the AI Act, since it does not:",
                "perform automated decision-making producing legal effects or similarly significant impacts on individuals (“an AI system… shall be considered to be high-risk where… it is intended to be used as a safety component of a product… and… subject to third-party conformity assessment” – Article 6(1); meaning only such systems qualify as high-risk).",
                "materially influence the outcome of decision-making or pose a significant risk to fundamental rights (“an AI system… shall not be considered to be high-risk where it does not pose a significant risk… including by not materially influencing the outcome of decision-making” – Article 6(3)).",
                "At the same time, the system complies with core regulatory principles reflected in the AI Act, including:",
                "Transparency obligations (“AI systems… [should be used] in a way that… makes humans aware that they interact with an AI system” – Recital 27; see also Article 50 on informing users of AI interaction).",
                "Clarity of system limitations (“the AI system is intended to improve the result of a previously completed human activity” and “is not meant to replace or influence… human assessment, without proper human review” – Article 6(3)(b) – (c)).",
                "Human autonomy protection (“AI-enabled manipulative techniques… may… impair autonomy, decision-making and free choice… and should therefore be prohibited” – Recital 29; see also Article 5(1)(a))."
            ]
        ),
        LegalSection(
            title: "Ukrainian Legal Context and Information Security",
            paragraphs: [
                "The platform considers Ukrainian legislation on information and national security, including:",
                "Law of Ukraine “On Information” (principles of information relations, including accuracy, completeness, and objectivity);",
                "Law of Ukraine “On National Security of Ukraine” (recognition of information threats as part of national security risks).",
                "In this context, disinformation constitutes a recognised challenge. However, the platform adopts a proportionate legal approach by enhancing information resilience through education rather than imposing restrictions on content.",
                "In addition, the platform considers Ukrainian copyright legislation, in particular the Law of Ukraine “On Copyright and Related Rights”.",
                "The platform uses content in a lawful manner, including:",
                "AI-generated materials;",
                "content used with permission or under applicable licences;",
                "and materials used in a limited and transformative way for educational purposes.",
                "The platform does not aim to reproduce or distribute copyrighted works as such, but rather to analyse and demonstrate patterns of disinformation, which reduces the risk of copyright infringement."
            ]
        ),
        LegalSection(
            title: "Liability and Risk Mitigation",
            paragraphs: [
                "The platform functions as an educational and AI-assisted decision-support tool and does not establish factual truth, in line with the principle that AI systems should support human decision-making rather than replace it (“AI should be a human-centric technology… serving as a tool for people” Recital 6,).",
                "In line with general principles reflected in European digital regulation, the system:",
                "does not produce binding or legally relevant decisions (“an AI system… shall not be considered to be high-risk where it does not… materially influence the outcome of decision-making” – Article 6(3));",
                "does not replace professional judgement (“AI literacy should… equip persons… to make informed decisions” – Recital 20);",
                "clearly communicates the probabilistic nature of outputs (“AI systems… should be used in a way that… makes humans aware that they interact with an AI system” – Recital 27; see also transparency obligations under Article 50).",
                "This approach reduces legal and ethical risks associated with misinformation, reputational harm, and overreliance on automated systems, in line with the objective of ensuring a high level of protection of fundamental rights (“to ensure a high level of protection of… fundamental rights” – Recital 1,).",
                "In addition to the risks outlined above, the platform also considers technical and algorithmic risks inherent to AI systems, particularly those based on machine learning models such as Support Vector Machines and transformer-based models (e.g., vector support machine, DistilBERT).",
                "These include:",
                "Algorithmic bias, where training data may introduce systematic distortions, potentially affecting the fairness and neutrality of outputs;",
                "False positives and false negatives, where the system may incorrectly identify or fail to identify manipulative content;",
                "Overgeneralization, particularly in natural language processing models, which may oversimplify complex statements or misinterpret context;",
                "Dataset limitations, including incomplete, outdated, or culturally biased training data;",
                "Lack of full explainability, due to the inherent complexity of machine learning models;",
                "Automation bias, where users may place excessive trust in AI-generated outputs;",
                "Risk of misuse, where outputs may be interpreted as authoritative or used outside the intended educational context.",
                "These risks are mitigated through transparency, probabilistic outputs, clear disclaimers, and a design focused on supporting rather than replacing human judgment."
            ]
        ),
        LegalSection(
            title: "Ethical and Legal Design Principles.",
            paragraphs: [
                "The platform is guided by the following legally relevant principles:",
                "Neutrality (no political or ideological bias);",
                "Transparency (clear explanation of outputs and AI involvement);",
                "User autonomy (no coercion or manipulation of user behaviour);",
                "Educational purpose (focus on skill development, not content control)."
            ]
        ),
        LegalSection(
            title: "Liability and Responsibility",
            paragraphs: [
                "The platform operates as an educational and AI-assisted decision-support tool and does not produce legally binding outcomes or definitive assessments of truth.",
                "Responsibility is distributed as follows:",
                "Provider (developer) is responsible for the design, transparency, and lawful functioning of the system, including clear communication of its limitations (“laying down uniform obligations for operators” – Recital 3, EU Artificial Intelligence Act);",
                "User/deployer is responsible for the interpretation and use of the outputs, particularly where such outputs are relied upon in external or professional contexts (the Regulation distinguishes roles of operators, including providers and deployers, Recital 12).",
                "In line with the EU Artificial Intelligence Act, liability does not arise from the mere use of AI, but from non-compliance with legal obligations, including misleading design or manipulative practices (“AI-enabled manipulative techniques… may impair autonomy… and should therefore be prohibited” – Recital 29; Article 5(1)(a)).",
                "Where user data is processed, responsibility also arises under the General Data Protection Regulation, in particular:",
                "lawful processing requirements (“processing shall be lawful… only if…” – Article 6);",
                "data protection principles (“personal data shall be… processed lawfully, fairly and in a transparent manner” – Article 5(1)(a)).",
                "The project reflects a balance between these principles: it does not restrict or control content, but instead enhances users’ ability to critically assess information, thereby supporting freedom of expression while minimising potential legal risks."
            ]
        )
    ]

    var body: some View {
        NavigationStack {
            ZStack {
                AppTheme.background
                    .ignoresSafeArea()

                ScrollView {
                    VStack(alignment: .leading, spacing: 20) {
                        Text("Legal")
                            .font(.largeTitle.bold())

                        Text("Open each section to read the full text.")
                            .font(.subheadline)
                            .foregroundStyle(.secondary)

                        ForEach(sections) { section in
                            LegalDropdownSection(
                                section: section,
                                isExpanded: expandedSections.contains(section.id)
                            ) {
                                toggle(section.id)
                            }
                        }
                    }
                    .padding(24)
                }
            }
        }
    }

    private func toggle(_ id: String) {
        withAnimation(.spring(response: 0.38, dampingFraction: 0.86)) {
            if expandedSections.contains(id) {
                expandedSections.remove(id)
            } else {
                expandedSections.insert(id)
            }
        }
    }
}

private struct LegalSection: Identifiable {
    let title: String
    let paragraphs: [String]

    var id: String { title }
}

private struct LegalDropdownSection: View {
    let section: LegalSection
    let isExpanded: Bool
    let action: () -> Void

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            Button(action: action) {
                HStack(spacing: 12) {
                    Text(section.title)
                        .font(.headline)
                        .multilineTextAlignment(.leading)

                    Spacer()

                    Image(systemName: "chevron.down")
                        .rotationEffect(.degrees(isExpanded ? 180 : 0))
                        .foregroundStyle(.indigo)
                }
                .padding(20)
                .contentShape(Rectangle())
            }
            .buttonStyle(.plain)

            if isExpanded {
                VStack(alignment: .leading, spacing: 14) {
                    ForEach(Array(section.paragraphs.enumerated()), id: \.offset) { index, paragraph in
                        Text(paragraph)
                            .font(.body)
                            .foregroundStyle(.primary)
                            .fixedSize(horizontal: false, vertical: true)
                            .transition(.opacity.combined(with: .offset(y: -10)))
                            .animation(
                                .easeOut(duration: 0.24).delay(Double(index) * 0.03),
                                value: isExpanded
                            )
                    }
                }
                .padding(.horizontal, 20)
                .padding(.bottom, 20)
                .clipped()
                .transition(
                    .asymmetric(
                        insertion: .opacity
                            .combined(with: .move(edge: .top))
                            .combined(with: .scale(scale: 0.98, anchor: .top)),
                        removal: .opacity
                    )
                )
            }
        }
        .background(AppTheme.quizContainer, in: RoundedRectangle(cornerRadius: 24, style: .continuous))
        .overlay(
            RoundedRectangle(cornerRadius: 24, style: .continuous)
                .stroke(Color.black.opacity(0.08), lineWidth: 1)
        )
        .animation(.spring(response: 0.38, dampingFraction: 0.86), value: isExpanded)
    }
}
